services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: bnhs-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: bnhs-web
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  # PostgreSQL Service
  db:
    image: postgres:15-alpine
    container_name: bnhs-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-postgres}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  # Queue Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bnhs-worker
    restart: unless-stopped
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    networks:
      - laravel

# Docker Networks
networks:
  laravel:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
